# Generated by Django 4.0.2 on 2022-02-03 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_comments_car_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_comment', to='accounts.car', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
