# Generated by Django 4.0.2 on 2022-02-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_car_comment_comments_car_alter_car_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',), 'verbose_name': 'Машины'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_comment', to='accounts.car', verbose_name='Машина'),
        ),
    ]
